### ISSUE TITLE
could not resolve plugin artifact

### ISSUE THREAD

**Issue by gabrieljones** [prokod/gradle-crossbuild-scala#96]
> Plugin [id: 'com.github.prokod.gradle-crossbuild-scala', version: '0.12.0'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'com.github.prokod.gradle-crossbuild-scala:com.github.prokod.gradle-crossbuild-scala.gradle.plugin:0.12.0')
>   Searched in the following repositories:
>     Gradle Central Plugin Repository

https://github.com/gabrieljones/crossbuild-hello/runs/1451175272?check_suite_focus=true
https://github.com/gabrieljones/crossbuild-hello/blob/64af4fc06da413108e5d9979a8b6fcc5f26ba811/build.gradle.kts

What did I do wrong?

**Comment by prokod** [comment]
@gabrieljones two things:
**First**: my bad on the documentation side, I though I have updated the plugin name in 0.12.0 but on Gradle Plugins repo it stayed as it was before, so to solve the first issue:
```
plugins {
  id("com.github.prokod.gradle-crossbuild") version "0.12.0"
}
```
**Second**: I have pulled you project - Thx for trying the plugin in Kotlin :) The Plugin API (which is Groovy based) is not prepared for easily access using Kotlin. The examples I have in documentation are for Groovy.
For instance, this from documentation
```
archivesBaseName = "crossbuild-hello"
```
Should be changed to
```
base {
  archivesBaseName = "crossbuild-hello"
}
```
But as I said, I will need to try and see how to correctly bypass DSL interoperability for the plugin itself
```
crossBuild {
  builds {
    scala {
      scalaVersions = ["2.11", "2.12", "2.13"]
    }
  }
}
```
I will add a task on the board to improve DSL interoperability and add Kotling DSL to documentation
Thx again for the valuable feedback!

**Comment by prokod** [comment]
@gabrieljones please see PR https://github.com/gabrieljones/crossbuild-hello/pull/1

**Comment by atais** [comment]
Sorry I still don't get how to use the plugin with kotlin DSL, should

```
crossBuild {
  builds {
    scala {
      scalaVersions = ["2.11", "2.12", "2.13"]
    }
  }
}
```
work?

I am trying to add this here: https://github.com/allure-framework/allure-java/blob/master/allure-scalatest/build.gradle.kts

and `project.base` prefix seems to be required for everything, yet `crossBuild` is not available there 

---

I think I've found my way inspired by:
- https://github.com/Jolanrensen/gradle-crossbuild-sample
- https://github.com/gabrieljones/crossbuild-hello
- https://github.com/newrelic/newrelic-java-agent/blob/scala3-cross-build/newrelic-scala-api/build.gradle.kts


```
plugins {
    scala
    id("com.github.prokod.gradle-crossbuild") version "0.16.0"
}

val scala212 = "2.12"
val scala213 = "2.13"

project.base.archivesName.set("allure-scalatest")

crossBuild {
    scalaVersionsCatalog = mapOf(
        scala212 to "2.12.19",
        scala213 to "2.13.14"
    )
    builds {
        register("scala") {
            scalaVersions = setOf(scala212, scala213)
        }
    }
}

val crossBuildScala_212Jar by tasks.getting
val crossBuildScala_213Jar by tasks.getting

publishing {
    publications {
        register("crossBuildScala_212", MavenPublication::class) {
            artifact(crossBuildScala_212Jar)
        }
        register("crossBuildScala_213", MavenPublication::class) {
            artifact(crossBuildScala_213Jar)
        }
    }
}
```

**Comment by prokod** [comment]
Hi there,

```
crossBuild {
        scalaVersionsCatalog = mapOf(
                "2.12" to "2.12.17",
                "2.13" to "2.13.12"
        )

        builds {
            create("v212")
            create("v213")
        }
    }
```
should work with Kotlin

Cheers
